merge dev

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,8 +3,9 @@ version: 2.1
 # These "CircleCI Orbs" are reusable bits of configuration that can be shared
 # across projects.  See https://circleci.com/orbs/ for more information.
 orbs:
-  gh: circleci/github-cli@2.2.0
-  slack: circleci/slack@4.12.5
+  gh: circleci/github-cli@2.3.0
+  slack: circleci/slack@4.12.6
+  secops: apollo/circleci-secops-orb@2.0.7
 
 executors:
   amd_linux_build: &amd_linux_build_executor
@@ -21,8 +22,8 @@ executors:
   amd_linux_test: &amd_linux_test_executor
     docker:
       - image: cimg/base:stable
-      - image: cimg/redis:7.2.3
-      - image: jaegertracing/all-in-one:1.51.0
+      - image: cimg/redis:7.2.4
+      - image: jaegertracing/all-in-one:1.53.0
     resource_class: xlarge
     environment:
       CARGO_BUILD_JOBS: 4
@@ -46,15 +47,15 @@ executors:
       # See https://circleci.com/docs/xcode-policy along with the support matrix
       # at https://circleci.com/docs/using-macos#supported-xcode-versions.
       # We use the major.minor notation to bring in compatible patches.
-      xcode: 13.4
-    resource_class: macos.x86.medium.gen2
+      xcode: 14.2
+    resource_class: macos.m1.medium.gen1
   macos_test: &macos_test_executor
     macos:
       # See https://circleci.com/docs/xcode-policy along with the support matrix
       # at https://circleci.com/docs/using-macos#supported-xcode-versions.
       # We use the major.minor notation to bring in compatible patches.
-      xcode: 13.4
-    resource_class: macos.x86.medium.gen2
+      xcode: 14.2
+    resource_class: macos.m1.medium.gen1
   windows_build: &windows_build_executor
     machine:
       image: "windows-server-2019-vs2019:stable"
@@ -658,6 +659,7 @@ jobs:
             and:
               - equal: [ *amd_linux_build_executor, << parameters.platform >> ]
               - equal: [ true, << parameters.nightly >> ]
+              - equal: [ "https://github.com/apollographql/router", << pipeline.project.git_url >> ]
           steps:
             - setup_remote_docker:
                 version: 20.10.11
@@ -678,9 +680,20 @@ jobs:
                   echo ${GITHUB_OCI_TOKEN} | docker login ghcr.io -u apollo-bot2 --password-stdin
                   # TODO: Can't figure out how to build multi-arch image from ARTIFACT_URL right now. Figure out later...
                   # Build and push debug image
-                  docker buildx build --platform linux/amd64 --push --build-arg ARTIFACT_URL="${ARTIFACT_URL}" --build-arg DEBUG_IMAGE="true" --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION}-debug .
+                  docker buildx build --load --platform linux/amd64 --build-arg ARTIFACT_URL="${ARTIFACT_URL}" --build-arg DEBUG_IMAGE="true" --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION}-debug .
+                  docker push ${ROUTER_TAG}:${VERSION}-debug
                   # Build and push release image
-                  docker buildx build --platform linux/amd64 --push --build-arg ARTIFACT_URL="${ARTIFACT_URL}" --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION} .
+                  docker buildx build --load --platform linux/amd64 --build-arg ARTIFACT_URL="${ARTIFACT_URL}" --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION} .
+                  docker push ${ROUTER_TAG}:${VERSION}
+                  # save containers for analysis
+                  mkdir built-containers
+                  docker save -o built-containers/router_${VERSION}-debug.tar ${ROUTER_TAG}:${VERSION}-debug
+                  docker save -o built-containers/router_${VERSION}.tar ${ROUTER_TAG}:${VERSION}  
+                 
+            - persist_to_workspace:
+                root: .
+                paths:
+                  - "built-containers/*.tar"
             - run:
                 name: Helm build
                 command: |
@@ -761,71 +774,83 @@ jobs:
       <<: *common_job_environment
       VERSION: << pipeline.git.tag >>
     steps:
-      - checkout
-      - setup_remote_docker:
-          version: 20.10.11
-          docker_layer_caching: true
-      - attach_workspace:
-          at: artifacts
-      - gh/setup
-      - run:
-          command: >
-            cd artifacts && sha256sum *.tar.gz > sha256sums.txt
-      - run:
-          command: >
-            cd artifacts && md5sum *.tar.gz > md5sums.txt
-      - run:
-          command: >
-            cd artifacts && sha1sum *.tar.gz > sha1sums.txt
-      - run:
-          name: Create GitHub Release
-          command: >
-            case "$VERSION" in
+      - when:
+          condition:
+            not:
+              equal: [ "https://github.com/apollographql/router", << pipeline.project.git_url >> ]
+          steps:
+             - run:
+                command: >
+                  echo "Not publishing any github release."
+      - when:
+          condition:
+            equal: [ "https://github.com/apollographql/router", << pipeline.project.git_url >> ]
+          steps:
+            - checkout
+            - setup_remote_docker:
+                version: 20.10.11
+                docker_layer_caching: true
+            - attach_workspace:
+                at: artifacts
+            - gh/setup
+            - run:
+                command: >
+                  cd artifacts && sha256sum *.tar.gz > sha256sums.txt
+            - run:
+                command: >
+                  cd artifacts && md5sum *.tar.gz > md5sums.txt
+            - run:
+                command: >
+                  cd artifacts && sha1sum *.tar.gz > sha1sums.txt
+            - run:
+                name: Create GitHub Release
+                command: >
+                  case "$VERSION" in
 
-              # If the VERSION contains a dash, consider it a pre-release version.
-              # This is in-line with SemVer's expectations/designations!
-              *-*) gh release create $VERSION --prerelease --notes-file /dev/null --title $VERSION artifacts/* ;;
+                    # If the VERSION contains a dash, consider it a pre-release version.
+                    # This is in-line with SemVer's expectations/designations!
+                    *-*) gh release create $VERSION --prerelease --notes-file /dev/null --title $VERSION artifacts/* ;;
 
-              # In all other cases, publish it as the latest version.
-              *) gh release create $VERSION --notes-file /dev/null --title $VERSION artifacts/* ;;
+                    # In all other cases, publish it as the latest version.
+                    *) gh release create $VERSION --notes-file /dev/null --title $VERSION artifacts/* ;;
 
-            esac
-      - run:
-          name: Docker build
-          command: |
-            ROUTER_TAG=ghcr.io/apollographql/router
-            # Create a multi-arch builder which works properly under qemu
-            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-            docker context create buildx-build
-            docker buildx create --driver docker-container --use buildx-build
-            docker buildx inspect --bootstrap
-            # Note: GH Token owned by apollo-bot2, no expire
-            echo ${GITHUB_OCI_TOKEN} | docker login ghcr.io -u apollo-bot2 --password-stdin
-            # To prevent overwrite, check to see if our images already exists
-            # If the manifest command succeeds, the images already exist
-            docker manifest inspect ${ROUTER_TAG}:${VERSION}  > /dev/null && exit 1
-            docker manifest inspect ${ROUTER_TAG}:${VERSION}-debug  > /dev/null && exit 1
-            # Build and push debug image
-            docker buildx build --platform linux/amd64,linux/arm64 --push --build-arg DEBUG_IMAGE="true" --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION}-debug .
-            # Build and push release image
-            docker buildx build --platform linux/amd64,linux/arm64 --push --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION} .
-      - run:
-          name: Helm build
-          command: |
-            # Install Helm
-            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
-            # Package up the helm chart
-            helm package helm/chart/router
-            # Make sure we have the newest chart
-            CHART=$(ls -t router*.tgz| head -1)
-            # Note: GH Token owned by apollo-bot2, no expire
-            echo ${GITHUB_OCI_TOKEN} | helm registry login -u apollo-bot2 --password-stdin ghcr.io
-            # To prevent overwrite, check to see if our chart already exists
-            # If the show all command succeeds, the chart already exists
-            VERSION=$(basename ${CHART} .tgz)
-            helm show all oci://ghcr.io/apollographql/helm-charts/router --version ${VERSION} > /dev/null && exit 1
-            # Push chart to repository
-            helm push ${CHART} oci://ghcr.io/apollographql/helm-charts
+                  esac
+            - run:
+                name: Docker build
+                command: |
+                  ROUTER_TAG=ghcr.io/apollographql/router
+                  # Create a multi-arch builder which works properly under qemu
+                  docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+                  docker context create buildx-build
+                  docker buildx create --driver docker-container --use buildx-build
+                  docker buildx inspect --bootstrap
+                  # Note: GH Token owned by apollo-bot2, no expire
+                  echo ${GITHUB_OCI_TOKEN} | docker login ghcr.io -u apollo-bot2 --password-stdin
+                  # To prevent overwrite, check to see if our images already exists
+                  # If the manifest command succeeds, the images already exist
+                  docker manifest inspect ${ROUTER_TAG}:${VERSION}  > /dev/null && exit 1
+                  docker manifest inspect ${ROUTER_TAG}:${VERSION}-debug  > /dev/null && exit 1
+                  # Build and push debug image
+                  docker buildx build --platform linux/amd64,linux/arm64 --push --build-arg DEBUG_IMAGE="true" --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION}-debug .
+                  # Build and push release image
+                  docker buildx build --platform linux/amd64,linux/arm64 --push --build-arg ROUTER_RELEASE=${VERSION} -f dockerfiles/Dockerfile.router -t ${ROUTER_TAG}:${VERSION} .
+            - run:
+                name: Helm build
+                command: |
+                  # Install Helm
+                  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+                  # Package up the helm chart
+                  helm package helm/chart/router
+                  # Make sure we have the newest chart
+                  CHART=$(ls -t router*.tgz| head -1)
+                  # Note: GH Token owned by apollo-bot2, no expire
+                  echo ${GITHUB_OCI_TOKEN} | helm registry login -u apollo-bot2 --password-stdin ghcr.io
+                  # To prevent overwrite, check to see if our chart already exists
+                  # If the show all command succeeds, the chart already exists
+                  VERSION=$(basename ${CHART} .tgz)
+                  helm show all oci://ghcr.io/apollographql/helm-charts/router --version ${VERSION} > /dev/null && exit 1
+                  # Push chart to repository
+                  helm push ${CHART} oci://ghcr.io/apollographql/helm-charts
 
 workflows:
   ci_checks:
@@ -908,6 +933,25 @@ workflows:
             parameters:
               platform:
                 [ macos_build, windows_build, amd_linux_build, arm_linux_build ]
+      - secops/wiz-docker:
+          context:
+            - platform-docker-ro
+            - wiz
+            - github-orb
+          requires:
+            - build_release
+          container-dir: /tmp/workspace/built-containers
+          # Disables all PR comments from this job
+          do-pr-comments: false
+          # Scan job will return 1 if findings violating the Wiz policy are found.
+          # Toggle off to prevent any CI failures OR 
+          # contact Apollo's Security team to adjust what violates the 
+          # Wiz policy used in this scan.
+          fail-on-findings: true
+          # Configure scan job to use a policy specific to apollo-router.
+          # This allows us to tailor the policy applied during the scans to router.
+          wiz-policies: Apollo-Router-Vulnerabilities-Policy
+
 
   release:
     when:
@@ -998,3 +1042,19 @@ workflows:
               ignore: /.*/
             tags:
               only: /v.*/
+  
+  security-scans:
+    when:
+      not: << pipeline.parameters.nightly >>
+    jobs:
+      - secops/gitleaks:
+          context:
+            - secops-oidc
+            - github-orb
+          git-base-revision: <<#pipeline.git.base_revision>><<pipeline.git.base_revision>><</pipeline.git.base_revision >>
+          git-revision: << pipeline.git.revision >>
+      - secops/semgrep:
+          context:
+            - secops-oidc
+            - github-orb
+          git-base-revision: <<#pipeline.git.base_revision>><<pipeline.git.base_revision>><</pipeline.git.base_revision >>
