feat: Upgrade apollo-router to version 1.27.0

diff --git a/dockerfiles/Dockerfile.router b/dockerfiles/Dockerfile.router
--- a/dockerfiles/Dockerfile.router
+++ b/dockerfiles/Dockerfile.router
@@ -1,40 +1,72 @@
-ARG DEBUG_IMAGE
-# Build is required to extract the release files
-FROM --platform=linux/amd64 alpine:latest AS build
+FROM debian:bullseye-slim AS downloader
+ARG ROUTER_RELEASE=latest
+ARG ARTIFACT_URL=
 
-ARG ROUTER_RELEASE
-
-# Pull release from GH
-ADD https://github.com/apollographql/router/releases/download/v${ROUTER_RELEASE}/router-${ROUTER_RELEASE}-x86_64-linux.tar.gz /tmp/router.tar.gz
-
-WORKDIR /tmp
-
-# router.tar.gz extracts to "dist"
-RUN tar xvzf router.tar.gz -C /
-
-# Make directories for config and schema
-RUN mkdir /dist/config && mkdir /dist/schema
-
-# Copy configuration for docker image
-COPY dockerfiles/router.yaml /dist/config
-
-# Required so we can copy in libz.so.1
-FROM --platform=linux/amd64 gcr.io/distroless/java17-debian11${DEBUG_IMAGE} as libz-required
-
-# Final image uses distroless
-FROM --platform=linux/amd64 gcr.io/distroless/cc-debian11${DEBUG_IMAGE}
-
-LABEL org.opencontainers.image.authors="ApolloGraphQL https://github.com/apollographql/router"
-
-# Copy in the extracted/created files
-COPY --from=libz-required /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1
-
-# Copy in the extracted/created files
-COPY --from=build --chown=root:root /dist /dist
+# Install curl
+RUN \
+  apt-get update -y \
+  && apt-get install -y \
+    curl
 
 WORKDIR /dist
 
+# Run the Router downloader which puts Router into current working directory
+RUN if [ -z "${ARTIFACT_URL}"]; then \
+    curl -sSL https://router.apollo.dev/download/nix/${ROUTER_RELEASE}/ | sh; \
+  else \
+    cd /; \
+    curl -sSL -o - ${ARTIFACT_URL} | tar -xzf -; \
+    cd -; \
+  fi
+
+FROM debian:bullseye-slim AS distro
+ARG DEBUG_IMAGE=false
+
+WORKDIR /dist
+
+COPY --from=downloader /dist/router /dist
+
+# Update apt and install ca-certificates
+RUN \
+  apt-get update -y \
+  && apt-get install -y \
+    ca-certificates
+
+# If debug image, install heaptrack and make a data directory
+RUN \
+  if [ "${DEBUG_IMAGE}" = "true" ]; then \
+    apt-get install -y heaptrack && \
+    mkdir data; \
+  fi
+
+# Clean up apt lists
+RUN rm -rf /var/lib/apt/lists/*
+
+# Make directories for config and schema
+RUN mkdir config schema
+
+# Copy configuration for docker image
+COPY dockerfiles/router.yaml config
+
+LABEL org.opencontainers.image.authors="Apollo Graph, Inc. https://github.com/apollographql/router"
+LABEL org.opencontainers.image.source="https://github.com/apollographql/router"
+
 ENV APOLLO_ROUTER_CONFIG_PATH="/dist/config/router.yaml"
 
-# Default executable is the router
-ENTRYPOINT ["./router"]
+# Create a wrapper script to run the router, use exec to ensure signals are handled correctly
+RUN \
+  echo '#!/usr/bin/env bash \
+\nset -e \
+\n \
+\nif [ -f "/usr/bin/heaptrack" ]; then \
+\n    exec heaptrack -o /dist/data/router_heaptrack /dist/router "$@" \
+\nelse \
+\n    exec /dist/router "$@" \
+\nfi \
+' > /dist/router_wrapper.sh
+
+# Make sure we can run our wrapper
+RUN chmod 755 /dist/router_wrapper.sh
+
+# Default executable is the wrapper script
+ENTRYPOINT ["/dist/router_wrapper.sh"]
